version: "3.1"
services:
  api:
    image: node:12-alpine3.9
    container_name: processor
    restart: always
    env_file:
     - .env
    network_mode: bridge
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app # toda essa pasta da app vai para o '/usr/src/app' no container
    working_dir: /usr/src/app
    command: npm run start:local
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"